### PR TITLE
160 hold off submitting scores for low commit submissions

### LINKED ISSUE #160: hold off submitting scores for low commit submissions
Requirements per the professors:
- Minimum requirement is 10 commits on at least 3 different days
- The autograder will enforce this and fail the submission with a message that they have to pass off in person
- The TA doing the in person grading can, at their discretion, deduct 10% if it looks like they are not learning the value/habit of repeated commits

### LINKED ISSUE #230: Backend: Finish deprecating the numCommits column from the Submissions table
This is no longer necessary since it was removed while resolving #160.

While we're at it, also finishing deprecating the `results` field in the Submissions DAO. @pawlh said he's nearly removed it, but we need to verify in the code that all references are cleaned up.

### PR DESCRIPTION
**Pull request by frozenfrank**
This code should receive and accept a low-commit submission from a student, and then continue processing the submission. It should report the low-commit submission, not report the grade to canvas, and alert the student to talk to a TA to receive credit.

Resolves #160, resolves #230.

This includes work from #284.

## Database modification
Run the following SQL statements to add new columns to the database
```sql
ALTER TABLE submission ADD `verified_status` VARCHAR(30);
ALTER TABLE submission ADD `verification` JSON;
ALTER TABLE submission DROP COLUMN `num_commits`;
ALTER TABLE submission DROP COLUMN `results`;
```

## TODO
- [ ] Verify that new submissions any applied penalty percentage from an earlier deduction.

### CODE REVIEW

**Comment by frozenfrank** [comment]
Note that we intend to use new adjustments from @19mdavenport to submit a comment to canvas reporting the adjustment even when a grade is not set.

**Comment by DallinFromEarth** [comment]
> If you could provide a link to the PR that contains the code, that may be helpful.

#234

**Comment by frozenfrank** [comment]
@pawlh I just pushed all my commits. I still have one more point to implement, but all the rest of the stuff should be working. 

I still don't have my machine set up to run the code yet so I was hoping you could run it and give me feedback. If not, I'll do my best.

I feel like I've done a good job on this so far. I would love your preliminary feedback as I near the final stage of this feature.

**Comment by frozenfrank** [comment]
@DallinFromEarth I haven't been able to locate the `unapproved` property of the submission. Is it already merged into `main`, or do we need to coordinate in some other way to make sure we're talking to each other?

**Comment by DallinFromEarth** [comment]
> @DallinFromEarth I haven't been able to locate the `unapproved` property of the submission. Is it already merged into `main`, or do we need to coordinate in some other way to make sure we're talking to each other?

It's not in main. I've just been coding with the assumption that it exists, but it will be really easy to change. I'll make my code fit to yours

**Comment by frozenfrank** [comment]
👍

File: src/main/java/edu/byu/cs/controller/SubmissionController.java [hunk 1]
```diff
@@ -370,4 +387,75 @@ public static void reRunSubmissionsInQueue() throws IOException {
...
+            approvedScore = SubmissionHelper.prepareModifiedScore(mostRecentPassingScoreOnPhase, scoreVerification);
+            // FIXME: Set `approvedScore` to the score of the most recent passing submission, multiplied by (1 - penaltyPct)
+            throw new RuntimeException("Dynamically determining approved score is not yet implemented");
+        }
+
+        // Update grade-book
+        CanvasIntegration canvasIntegration = CanvasService.getCanvasIntegration();
+        // FIXME: Store `approvedScore` in the Grade-book
+        // canvasIntegration.submitGrade(studentNetId, approvedScore, );
+        throw new RuntimeException("ApproveSubmission not implemented!"); // TODO: Finish implementing method
```
Comment (frozenfrank) [inline src/main/java/edu/byu/cs/controller/SubmissionController.java:454]: This is causing the checks to fail.

File: src/test/java/edu/byu/cs/autograder/score/ScorerTest.java
Comment (frozenfrank) [inline src/test/java/edu/byu/cs/autograder/score/ScorerTest.java:1]: This file is causing the checks to fail.

**Comment by frozenfrank** [comment]
@pawlh @19mdavenport With the addition of the last two merge commits, I've been able to confirm that this is working properly and doesn't crash the system. I also added several SQL statements to this PR description that will modify existing databases with the new columns.

I'm now continuing to build several test cases to more completely verify that the code is behaving the way we want it to.

At this point, I would love your comments and feedback on the code while I work on the tests.

File: src/main/java/edu/byu/cs/autograder/git/specs.md [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+
+## Recommendation
+Based on all the information above, I propose the following:
+1. We count only commits towards the commit limit if they were authored after **the most recent timestamp of the commit of any commit that resulted in an accepted submission from any phase**.
+2. We throw an error and refuse to grade if we detect any commits that are authored before their parent commit (indicates intentionally messing with the local clock, or cherry-picking commits).
+3. We withhold the score as “not qualified” if any of the commits are authored in the future of the server timestamp (indicates messing with the local clock, or it could be a simple mistake).
+4. We explicitly preserve a student’s commit verification result for any subsequent submissions on the same phase. I.E. If they pass on their first valid submission, then we’ll continue passing them even if they are resubmitting to fix quality errors etc… And, if they fail on their first submissions, they’ll be able to continue resubmitting, but none of those grades will be submitted to Canvas even if they are resolving quality errors.
```
Comment (pawlh) [inline src/main/java/edu/byu/cs/autograder/git/specs.md:21]: I agree that this is the only way to fight against fake commits and should be implemented, but this could cause a very confusing experience for users. There will need to be very clear instruction both in class, on GitHub, and on the autograder explaining this rule

File: src/main/java/edu/byu/cs/autograder/git/specs.md [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+7. Students cannot resubmit their code to the autograder with an earlier passing commit in order to count more commits as credit for the current phase. If we only evaluated the most recent passing submission, then a student could push their maximum time back by resubmitting with an earlier commit that still passes. Even if the commit lowers results in a lower score (from quality checks etc…), this wouldn't hurt them since we don’t send lower scores to Canvas.
+
+### Shortcomings
+1. It does not protect against a student modifying **all the commit timestamps** of their code block by a fixed amount, but if a student is familiar enough with git to do such an advanced operation, they probably deserve to keep their points gained.
+2. Additionally, any student who was not intentionally breaking the system but accidentally has their clock set forward for some reason (I’ve done that before) would be prevented from having their submission graded.
+3. Students who cherry-pick commits out of chronological order will be prevented from grading.
+4. This still assumes that students submit the phases in order (probably safe).
```
Comment (pawlh) [inline src/main/java/edu/byu/cs/autograder/git/specs.md:36]: I agree this is probably safe. I believe that we've discussed enforcing this formally, but have hesitated doing so because students have not been informed of this policy. Again, I think this will require clear and deliberate communicate with the students as an accompanying change should be made to make this be formally enforced

**Comment by 19mdavenport** [comment]
Is this completed and ready to merge in?

**Comment by frozenfrank** [comment]
> Is this completed and ready to merge in?

It's ready for review. I've tested it manually, and I'm writing unit tests for it in #336. I expect it to work, but I want someone to double check my work. I would be able to confidently say "yes" when I finish the above PR.

Can you give it a couple tests and verify it works for you too?

(I also see that there are some new merge conflicts.)

**Comment by 19mdavenport** [comment]
What do we want to happen if a student has to change repositories or force push a different commit (or uses a different branch)?
image

**Comment by 19mdavenport** [comment]
Also, do we want to say "Passed with X%", or would it be helpful to replace that message with something? I'm just worried that some people won't read the rest of the notes if they see the word "passed", and then email us later asking what happened

**Review by 19mdavenport — APPROVED** [review]
This all looks reasonable to me, unless you are aware of any other potential problems?

File: src/main/java/edu/byu/cs/autograder/git/specs.md (hunk 2 above)
Comment (frozenfrank) [reply src/main/java/edu/byu/cs/autograder/git/specs.md:21]: I've done my best to provide helpful error messages. For example, the autograder will report the following in the notes which go to Canvas:

> Commit history approved with a penalty of 10%

File: src/main/java/edu/byu/cs/autograder/git/specs.md (hunk 3 above)
Comment (frozenfrank) [reply src/main/java/edu/byu/cs/autograder/git/specs.md:38]: The students will either figure it out quickly, or they'll talk to the TA's and not lose any points in the end. I think this is a reasonable assumption to make.
